ctx.addClock("iclk", 36)
ctx.addClock("oclk_sd", 18)
ctx.addClock("sd_inst.clock_divider_inst.clk_18MHz", 18)
ctx.addClock("sd_inst.clock_divider_inst.clk_281kHz", 0.281)
ctx.addClock("sd_inst.clk_sd", 18)
